events {}

http {
  server { #cria servidor
    listen 80; #escuta na porta 80

    location / {
      proxy_pass http://app:3000; #Cliente → Nginx (porta 80) → Node (porta 3000)
      proxy_set_header Host $host; #Envia o host original para o Node
      proxy_set_header X-Real-IP $remote_addr; #envia IP original
    }
  }
}