version: '3.8'

services:
  app:
    build: ./app
    container_name: fastbite_app
    restart: always
    networks:
      - fastbite_net

  nginx:
    image: nginx:alpine
    container_name: fastbite_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - fastbite_net

networks:
  fastbite_net:
    driver: bridge